### ISSUE TITLE
a simple reading example?

### ISSUE THREAD

**Issue by hugoledoux** [tmontaigu/laz-rs#11]
I'd like to use your library but I've never dived in the gory details of LAZ, and I am honestly not that interested...

I'd just like to read my LAZ files, but now with the example you give I get a vector with values, and I am not sure what to do with those. I'd like to read a LAZ file and iterate over all the points and get their (x,y,z) and the attributes.

Possible to put a simple example?

**Comment by tmontaigu** [comment]
At the moment, this library is designed to be used by libraries that implements LAS file reading/writing to also be able to  readwrite LAZ files.

So it is probably not going to be useful directly to you.

If you want to read LAS files in Rust there is already las-rs ([github](https://github.com/gadomski/las-rs) [crate.io](https://crates.io/crates/las)) which when compiled with the `laz` feature can read and write LAZ files by using this lib.

**Comment by hugoledoux** [comment]
Oh, I hadn’t realised that that library does LAZ!?

You guys should advertise more, I tried and it’s great and works!

Perhaps explaining how to compile with laz-rs would help, I didn’t know about the ‘—features’, in surely not the only one..

**Comment by tmontaigu** [comment]
Ya the suport for LAZ in las-rs via a fearure is mentionned once in the docs and its kinda buried so you don't see it
