### ISSUE TITLE
Make `LasZipDecompressor` `Send`

### ISSUE THREAD

**Issue by Mortano** [tmontaigu/laz-rs#16]
I am trying to use your library (through the `las-rs` crate) in a multithreaded context. I am having problems to do so because the `LasZipDecompressor` struct is not `Send` (because it is storing a `Box<dyn RecordDecompressor>` and the `RecordDecompressor` trait is not `Send`). 

As far as I can tell, it would be possible to make `LasZipDecompressor` `Send`, which would make it possible to use it in a multithreaded context. I implemented what I believe to be the necessary changes in a fork here: https://github.com/Mortano/laz-rs/tree/make-decompressor-send 

Let me know if this is a sensible change. It might also be worth discussing if these changes should be applied to the `...Compressor` types as well. 

I also opened a similar issue for the `las-rs` crate [here](https://github.com/gadomski/las-rs/issues/33), just for reference.

**Comment by tmontaigu** [comment]
Hello,

Do you have a small example of what you are trying to do ?

I looked at your fork, I wonder if adding 
```Rust
unsafe impl<'a, R: Send + Read + Seek + 'a> Send for LasZipDecompressor<'a, R> {}
```
would work and reduce the repetition of  `Send`.


And if we make LasZipDecompressor `Send`  then LasZipCompressir shall also be `Send`.
